main/urls.py
from django.conf.urls import patterns, url

from main.views import MainPageView, OrderView, ReadView, SupportView
import main.views

urlpatterns = patterns('',
  url(r'^$', MainPageView.as_view(), name = "main"),
  url(r'^booksdetail/pdf/$', main.views.someview, name = "pdfu"),
  url(r'^booksdetail/time/$', "main.views.timeview", name = "timeu"),
  url(r'^booksdetail/order/$', OrderView.as_view(), name = "orderview"),
  url(r'^booksdetail/read/$', ReadView.as_view(), name = "readview"),
  url(r'^booksdetail/support/$', SupportView.as_view(), name = "supportview"),

)

medik/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from contacts.views import ContactsView
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'medik.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('main.urls')),
    url(r'^archive/', include('author.urls')),
    url(r'^author/', include('author.urls')),
    url(r'^item2/(?P<alias>[^/]+)', 'author.views.item2'),
    url(r'^contacts/', ContactsView.as_view(), name = "contacts"),
    url(r'^news/', include('news.urls')),
    url(r'^booksdetail/(?P<book_id>\d+)/$', 'main.views.booksdetail', name = "booksdetail1"),
    url(r'^booksdetail/addcomment/(?P<book_id>\d+)/$', 'main.views.addcomment'),









)

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
# -*- coding: utf-8 -*-
from django.db import models


from django.contrib.comments.moderation import CommentModerator, moderator
from django.core.urlresolvers import reverse



class Books(models.Model):
  name = models.CharField(max_length = 150, unique = True, db_index = True, verbose_name = "Название")
  author = models.CharField(max_length = 30, unique = False, db_index = True, verbose_name = "Автор")
  theme = models.CharField(max_length = 100, unique = False, db_index = True, verbose_name = "Тематика")
  edition = models.CharField(max_length = 100, unique = False, db_index = True, verbose_name = "Вид издания")
  isbn = models.CharField(max_length = 30, unique = True, db_index = True, verbose_name = "ISBN")
  tags = models.CharField(max_length = 100, unique = False, db_index = True, verbose_name = "Теги")
  holder = models.CharField(max_length = 100, unique = False, db_index = True, verbose_name = "Правообладатель")
  release = models.DateField(db_index = True, verbose_name = "Год выпуска")
  form = models.CharField(max_length = 15, unique = False, db_index = True, verbose_name = "Формат")
  number = models.CharField(max_length = 30, unique = False, db_index = True, verbose_name = "Объем")
  image = models.ImageField(upload_to = "books/list", verbose_name = "Основное изображение")
  about = models.TextField(verbose_name = "От автора")
  alias = models.SlugField(verbose_name='Alias книги')
  def __unicode__(self):
        return self.name
  class Meta:
        verbose_name="Книга"
        verbose_name_plural="Книги"

class Guestbook(models.Model):
  books = models.ForeignKey(Books, verbose_name = "Книга")
  user = models.CharField(max_length = 20, verbose_name = "Пользователь")
  posted = models.DateTimeField(auto_now_add = True, db_index = True, verbose_name = "Опубликовано")
  content = models.TextField(verbose_name = "Отзыв")


  class Meta:
        verbose_name="Отзыв"
        verbose_name_plural="Отзывы"



class Country(models.Model):
  name = models.CharField(max_length = 150, unique = True, db_index = True, verbose_name = "Название")
  def __unicode__(self):
        return self.name
  class Meta:
        verbose_name="Страна доставки"
        verbose_name_plural="Страны доставки"

class Order(models.Model):
  books = models.ForeignKey(Books, verbose_name = "Книга")
  qty = models.PositiveIntegerField(default=1, max_length = 7, unique = False, db_index = True, verbose_name = "Количество экземпляров")
  post_index = models.PositiveIntegerField(max_length = 6, unique = False, db_index = True, verbose_name = "Почтовый индекс")
  country = models.ForeignKey(Country, verbose_name = "Страна")
  address = models.CharField(max_length = 100, unique = False, db_index = True, verbose_name = "Адрес доставки")
  fio = models.CharField(max_length = 50, unique = False, db_index = True, verbose_name = "Ваше ФИО")
  mail = models.EmailField(unique = False, db_index = True, verbose_name = "E-mail для связи")
  comment = models.TextField(verbose_name = "Комментарий")

  class Meta:
        verbose_name="Заказ"
        verbose_name_plural="Заказы"

news/models.py
# -*- coding: utf-8 -*-
from django.db import models

from datetime import datetime

class New(models.Model):
  title = models.CharField(max_length = 100, unique_for_date = "posted", verbose_name = "Заголовок")
  description = models.TextField(verbose_name = "Краткое содержание")
  content = models.TextField(verbose_name = "Полное содержание")
  posted = models.DateTimeField(default = datetime.now(), db_index = True, verbose_name = "Опубликована")

  class Meta:
    ordering = ["-posted"]
    verbose_name = "новость"
    verbose_name_plural = "новости"

main/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm, TextInput, Textarea

from main.models import Guestbook, Order, Books, Country

class BookForm(forms.ModelForm):
    class Meta:
        fields = ['user', 'content']
        model = Guestbook

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['books', 'qty','fio', 'mail','country','post_index', 'address','comment' ]
        widgets = {'post_index':TextInput(attrs={'cols': 80, 'rows': 20}),}
    honeypot = forms.CharField(required=False, label='Ловушка для спамеров')
    def clean_email(self):
        data = self.cleaned_data['qty']
        if data > 0:
            raise forms.ValidationError("Пожалуйста используйте fred@mail.ru адрес")
        return data

main/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

from django.views.generic.base import TemplateView
from contacts.views import CategoryListMixin
#from generic.controllers import PageNumberView
from django.views.generic.list import ListView
from main.models import Books
from main.forms import BookForm
from django.views.generic.base import View
from django.views.generic.dates import ArchiveIndexView
from django.views.generic import ListView
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template.loader import render_to_string
from django.shortcuts import render_to_response, redirect
from main.forms import BookForm, OrderForm
from django.core.context_processors import csrf
from main.models import Guestbook, Order
from io import BytesIO
from reportlab.pdfgen import canvas
from django.http import HttpResponse
from reportlab.lib.units import cm
import datetime
from django.contrib import messages

class PageNumberView(View):
  def get(self, request, *args, **kwargs):
    try:
      self.sort = self.request.GET["sort"]
    except KeyError:
      self.sort = "0"
    try:
      self.order = self.request.GET["order"]
    except KeyError:
      self.order = "A"
    try:
      self.search = self.request.GET["search"]
    except KeyError:
      self.search = ""
    try:
      self.tag = self.request.GET["tag"]
    except KeyError:
      self.tag = ""
    return super(PageNumberView, self).get(request, *args, **kwargs)

  def post(self, request, *args, **kwargs):
    try:
      pn = request.GET["page"]
    except KeyError:
      pn = "1"
    self.success_url = self.success_url + "?page=" + pn
    try:
      self.success_url = self.success_url + "&search=" + request.GET["search"]
    except KeyError:
      pass
    try:
      self.success_url = self.success_url + "&tag=" + request.GET["tag"]
    except KeyError:
      pass
    return super(PageNumberView, self).post(request, *args, **kwargs)



class MainPageView(ListView, CategoryListMixin):
  template_name = "mainpage.html"
  model = Books
  context_object_name = 'main_books'
  allow_empty = True
  allow_future = True




def booksdetail(request, book_id):
    book_form = BookForm
    args = {}
    args.update(csrf(request))
    args['name_context'] = Books.objects.get(id=book_id)
    args['comments'] = Guestbook.objects.filter(books_id=book_id)
    args['form'] = book_form
    args['num_comments'] = Guestbook.objects.filter(books_id=book_id).count()
    return render_to_response('booksdetail.html', args)


def addcomment(request, book_id):
    if request.POST:
        form = BookForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.books = Books.objects.get(id=book_id)
            form.save()
    return redirect('/booksdetail/%s' % book_id)

def someview(request):
    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'

    buffer = BytesIO()

    # Create the PDF object, using the BytesIO object as its "file."
    p = canvas.Canvas(buffer)
    p.setLineWidth(.3)
    p.setFont('Helvetica', 12)

    p.drawString(30,750,'OFFICIAL COMMUNIQUE')
    p.drawString(30,735,'OF ACME INDUSTRIES')
    p.drawString(500,750,"12/12/2010")
    p.line(480,747,580,747)

    p.drawString(275,725,'AMOUNT OWED:')
    p.drawString(500,725,"$1,000.00")
    p.line(378,723,580,723)

    p.drawString(30,703,'RECEIVED BY:')
    p.line(120,700,580,700)
    p.drawString(120,703,"JOHN DOE")
    p.save()

    # Get the value of the BytesIO buffer and write it to the response.
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response

def timeview(request):
    now = datetime.datetime.now()
    html = "<html><body>Сейчас %s.</body></html>" % now
    return HttpResponse(html)

class OrderView(TemplateView):
    model = Order
    template_name = "order.html"
    form = None
    def get(self, request, *args, **kwargs):
        self.form = OrderForm()
        return super(OrderView, self).get(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data(**kwargs)
        context["form"] = self.form
        return context
    def post(self, request, *args, **kwargs):
        self.form = OrderForm(request.POST)
        if self.form.is_valid():
            if self.form.cleaned_data["honeypot"] == "":
                if self.form['qty'] > 0:
                    self.form.save()
                    messages.add_message(request, messages.SUCCESS, "Заказ успешно отправлен.")
                return redirect("main")
        else:
            return super(OrderView, self).get(request, *args, **kwargs)

class ReadView(TemplateView):
    template_name = "read.html"


class SupportView(TemplateView):
    template_name = "support.html"

templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link type="text/css" href="{% static "base.css" %}" rel="stylesheet">
    <script src="{% static 'jquery.js' %}"></script>

    {% block additional_css %}
    {% endblock %}
    {% block additional_js %}
    {% endblock %}
    <title>{% block title %}медик{% endblock %}  Копьев Юрий Павлович</title>
  </head>
  <body>
   {% block content %}


    <div class="container">
      <div class="gfx"><span></span></div>
      <div class="top">
          {%block menu%}
            {%include "menu.html"%}
          {%endblock menu%}
        <div class="pattern"><span></span></div>
        <div class="header">
          <h1>Копьев </h1>
          <h1>Юрий Павлович</h1>
          <p>врач, исследователь, писатель</p>
        </div>
        <div class="pattern"><span></span></div>
      </div>
      <div class="content">
        <div class="spacer"></div>

          <div class="body">

        <div class="divider"><span></span></div>
        <div class="item">


                 {% block main %}
                  {% endblock %}

        </div>


      <div class="footer">  <p>Все права принадлежат разработчикам сайта.</p> </div>
        </div>

{% endblock %}

  </body>
</html>

templates/main.html
{% extends "base.html" %}
{% load staticfiles %}
{% block additional_css %}
  <link type="text/css" href="{% static "default.css"  %}" rel="stylesheet">
{% endblock %}
{% block additional_js %}
{% endblock %}
{%block menu%}
  {%include "menu.html" with is_main=True%}
{%endblock menu%}
{% block main %}
{% endblock %}
<div id="main">

  </div>
  <div id="footer">



  </div>

templates/news_index.html
{% extends "main.html" %}
{% load staticfiles %}
{% block title %}Новости{% endblock %}
{%block menu%}
    {%include "menu.html" with is_news=True%}
{%endblock menu%}
{% block main %}
  {% include "generic/messages.html" %}
  <h1>Новости</h1><br>
  {% if perms.news.add_new %}
    <p><a href="{% url "news_add" %}">Добавить новость</a></p>
  {% endif %}
  <div class="feeds">

  </div>
  {% for object in latest %}
    <div class="news_content">
    <h4 class="newstitle"><a href="{% url "news_detail" pk=object.pk %}?page={{ page_obj.number }}">{{ object.title }}</a></h4>
    <p class="posted">{{ object.posted|date:"j.m.Y H:i" }}</p><br><br>
    <p>{{ object.description}}</p>

    <p class="buttons bottom-indent">
      {% if perms.news.change_new %}
        <a href="{% url "news_edit" pk=object.pk %}?page={{ page_obj.number }}">Изменить</a>
      {% endif %}
      {% if perms.news.delete_new %}
        <a href="{% url "news_delete" pk=object.pk %}?page={{ page_obj.number }}">Удалить</a>
      {% endif %}
    </p>
    </div>
  {% endfor %}
  {% include "generic/pagination.html" %}
{% endblock %}